// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gps_app.Persistency;

#nullable disable

namespace gps_app.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gps_app.Models.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = "D-1567",
                            DeviceType = "Aircraft"
                        },
                        new
                        {
                            Id = "D-1568",
                            DeviceType = "Personal"
                        },
                        new
                        {
                            Id = "D-1569",
                            DeviceType = "Asset"
                        },
                        new
                        {
                            Id = "D-1570",
                            DeviceType = "Personal"
                        },
                        new
                        {
                            Id = "D-1571",
                            DeviceType = "Asset"
                        });
                });

            modelBuilder.Entity("gps_app.Models.DeviceData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceData");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Date = new DateTime(2022, 8, 31, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1567",
                            Location = "L1"
                        },
                        new
                        {
                            Id = "2",
                            Date = new DateTime(2022, 8, 31, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1567",
                            Location = "L1"
                        },
                        new
                        {
                            Id = "3",
                            Date = new DateTime(2022, 8, 31, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1567",
                            Location = "L1"
                        },
                        new
                        {
                            Id = "4",
                            Date = new DateTime(2022, 8, 31, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1567",
                            Location = "L1"
                        },
                        new
                        {
                            Id = "5",
                            Date = new DateTime(2022, 8, 31, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1567",
                            Location = "L2"
                        },
                        new
                        {
                            Id = "6",
                            Date = new DateTime(2022, 8, 31, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1568",
                            Location = "L3"
                        },
                        new
                        {
                            Id = "7",
                            Date = new DateTime(2022, 8, 31, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1568",
                            Location = "L3"
                        },
                        new
                        {
                            Id = "8",
                            Date = new DateTime(2022, 8, 31, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1568",
                            Location = "L3"
                        },
                        new
                        {
                            Id = "9",
                            Date = new DateTime(2022, 8, 31, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1568",
                            Location = "L3"
                        },
                        new
                        {
                            Id = "10",
                            Date = new DateTime(2022, 8, 31, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1568",
                            Location = "L3"
                        },
                        new
                        {
                            Id = "11",
                            Date = new DateTime(2022, 8, 31, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1569",
                            Location = "L4"
                        },
                        new
                        {
                            Id = "12",
                            Date = new DateTime(2022, 8, 31, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1569",
                            Location = "L4"
                        },
                        new
                        {
                            Id = "13",
                            Date = new DateTime(2022, 8, 31, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1569",
                            Location = "L1"
                        },
                        new
                        {
                            Id = "14",
                            Date = new DateTime(2022, 8, 31, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1569",
                            Location = "L1"
                        },
                        new
                        {
                            Id = "15",
                            Date = new DateTime(2022, 8, 31, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1570",
                            Location = "L5"
                        },
                        new
                        {
                            Id = "16",
                            Date = new DateTime(2022, 8, 31, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = "D-1571",
                            Location = "L6"
                        });
                });

            modelBuilder.Entity("gps_app.Models.DeviceData", b =>
                {
                    b.HasOne("gps_app.Models.Device", "Device")
                        .WithMany("DeviceData")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("gps_app.Models.Device", b =>
                {
                    b.Navigation("DeviceData");
                });
#pragma warning restore 612, 618
        }
    }
}
